
version: '3.7'

services:
  postgres:
    image: postgres:latest
    container_name: jo-ken-po-db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - '5432:5432'
