# Routes

## Game

### Create game
POST http://localhost:3000/games
content-type: application/json

### Get all games
GET http://localhost:3000/games
content-type: application/json

### Get game by id
GET http://localhost:3000/games/48afbfbb-09db-41d5-a40a-5b4b530cab1a
content-type: application/json

### Restart game
PUT http://localhost:3000/games/37d432f7-5d6a-4906-a7d6-f02bb1f9c555/restart
content-type: application/json

## Game player

### Add player in the game
POST http://localhost:3000/games/48afbfbb-09db-41d5-a40a-5b4b530cab1a/player
content-type: application/json

{
  "username": "fulanin"
}

### Player play
PATCH http://localhost:3000/games/48afbfbb-09db-41d5-a40a-5b4b530cab1a/player/fulanin
content-type: application/json

{
  "pick": "PO"
}
