# Routes

## Game - Jo Ken Po

### Create game
POST http://localhost:3000/games
content-type: application/json

### Get game by id
GET http://localhost:3000/games/5f61b7bc-90cf-4d4f-b0d1-e3c70acbf85c
content-type: application/json

### Add player in the game
POST http://localhost:3000/games/5f61b7bc-90cf-4d4f-b0d1-e3c70acbf85c/player
content-type: application/json

{
  "username": "fulanin2"
}

### Player play
PATCH http://localhost:3000/games/5f61b7bc-90cf-4d4f-b0d1-e3c70acbf85c/player/09fa7a82-2108-44d4-b323-7a9758fc2f04
content-type: application/json

{
  "pick": "PO"
}

### Finish game
PUT http://localhost:3000/games/5f61b7bc-90cf-4d4f-b0d1-e3c70acbf85c/finish
content-type: application/json
