name: Build and Deploy to PRD

on:
  workflow_dispatch:
  push:
    branches: ["master"]

jobs:
  build:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 18.9.0
        uses: actions/setup-node@v3
        with:
          node-version: 18.9.0
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Start postgres container
        run: docker-compose up -d postgres

      - name: Create .env
        run: cat .env.example > .env

      - name: Run prisma generate
        run: npx prisma generate

      - name: Run pisma migrate
        run: npx prisma migrate deploy

      - name: Run tests
        run: npm test

      - name: Run build
        run: npm run build

      - name: Stop postgres container
        if: always()
        run: docker-compose -f down

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Wait for Render Deployment
        uses: bounceapp/render-action@0.6.0
        with:
          render-token: ${{ secrets.RENDER_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          service-id: ${{ secrets.RENDER_SERVICE_ID }}
